const questionTwo = (limit) => {
    let sum=0
    let a = 1 
    let b = 2
    let c = 0 

    if (limit >= 2) {
        console.log("this is sum "+sum)
        console.log("this is b " + b)
        console.log("this is a " + a)
        sum = sum + b
    }
    while (c <= limit) {
        c = a + b
        if (c % 2 === 0) {
            sum = sum + c
        }
        a = b
        b = c
    }
    console.log(sum)
    return sum
}

questionTwo(4000000)

//https://projecteuler.net/problem=2
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/  